"""
NPK Fantasy Football Roster & Draft Archive
Stores a rolling 2-year window of draft results and team baseline rosters.
"""

# Normalized 12 League Teams (reflecting name updates: hurts so good -> The Mad Scientist Syndicate, Dream killer -> ninja)
TEAMS = [
    "Jack Wagons",
    "MotorBoaters",
    "ninja",
    "RAZINUDOWN",
    "Samurai",
    "SilentXecution",
    "Super Saiyan",
    "Tbone Diva Manglers",
    "TD Master",
    "The Cinderella Boyz",
    "The Mad Scientist Syndicate",
    "Wild Card",
]

# Historical multi-year keeper status prior to the 2026 draft
# Format: (Player Name, Team): {"years_kept": int, "initial_draft_round": int, "is_undrafted": bool}
KEEPER_HISTORY = {
    ("CeeDee Lamb", "ninja"): {"years_kept": 4, "prior_cost": 1, "is_undrafted": False},
    ("Quay Walker", "ninja"): {"years_kept": 2, "prior_cost": 16, "is_undrafted": False},
    ("Devin Lloyd", "ninja"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Saquon Barkley", "The Mad Scientist Syndicate"): {"years_kept": 5, "prior_cost": 1, "is_undrafted": False},
    ("Julian Love", "The Mad Scientist Syndicate"): {"years_kept": 2, "prior_cost": 11, "is_undrafted": False},
    ("Jaxson Dart", "The Mad Scientist Syndicate"): {"years_kept": 2, "prior_cost": 13, "is_undrafted": True},
    ("Tremaine Edmunds", "The Mad Scientist Syndicate"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Jonathan Taylor", "Jack Wagons"): {"years_kept": 2, "prior_cost": 1, "is_undrafted": False},
    ("Maxx Crosby", "Jack Wagons"): {"years_kept": 6, "prior_cost": 7, "is_undrafted": True},
    ("Jakobi Meyers", "Jack Wagons"): {"years_kept": 3, "prior_cost": 12, "is_undrafted": False},
    ("Nate Landman", "Jack Wagons"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Jaxon Smith-Njigba", "MotorBoaters"): {"years_kept": 2, "prior_cost": 3, "is_undrafted": False},
    ("Edgerrin Cooper", "MotorBoaters"): {"years_kept": 2, "prior_cost": 8, "is_undrafted": False},
    ("Dalton Kincaid", "MotorBoaters"): {"years_kept": 2, "prior_cost": 11, "is_undrafted": False},
    ("Tyrel Dodson", "MotorBoaters"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Brock Bowers", "RAZINUDOWN"): {"years_kept": 3, "prior_cost": 4, "is_undrafted": False},
    ("Chimere Dike", "RAZINUDOWN"): {"years_kept": 2, "prior_cost": 13, "is_undrafted": True},
    ("Jamien Sherwood", "RAZINUDOWN"): {"years_kept": 3, "prior_cost": 13, "is_undrafted": True},
    ("Tuli Tuipulotu", "RAZINUDOWN"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Trey McBride", "Samurai"): {"years_kept": 4, "prior_cost": 4, "is_undrafted": True},
    ("Rashee Rice", "Samurai"): {"years_kept": 2, "prior_cost": 7, "is_undrafted": False},
    ("Carson Schwesinger", "Samurai"): {"years_kept": 2, "prior_cost": 12, "is_undrafted": False},
    ("Cam Skattebo", "Samurai"): {"years_kept": 2, "prior_cost": 13, "is_undrafted": False},
    ("Cedric Gray", "Samurai"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Garrett Wilson", "SilentXecution"): {"years_kept": 2, "prior_cost": 3, "is_undrafted": False},
    ("Chris Olave", "SilentXecution"): {"years_kept": 2, "prior_cost": 5, "is_undrafted": False},
    ("Ernest Jones IV", "SilentXecution"): {"years_kept": 2, "prior_cost": 12, "is_undrafted": False},
    ("Jordan Battle", "SilentXecution"): {"years_kept": 2, "prior_cost": 17, "is_undrafted": False},
    ("Bijan Robinson", "Super Saiyan"): {"years_kept": 5, "prior_cost": 1, "is_undrafted": False},
    ("Jordyn Brooks", "Super Saiyan"): {"years_kept": 3, "prior_cost": 9, "is_undrafted": False},
    ("Rome Odunze", "Super Saiyan"): {"years_kept": 2, "prior_cost": 10, "is_undrafted": False},
    ("Zack Baun", "Super Saiyan"): {"years_kept": 3, "prior_cost": 13, "is_undrafted": True},
    ("Ja'Marr Chase", "Tbone Diva Manglers"): {"years_kept": 4, "prior_cost": 1, "is_undrafted": False},
    ("Zaire Franklin", "Tbone Diva Manglers"): {"years_kept": 5, "prior_cost": 9, "is_undrafted": True},
    ("Devin Bush", "Tbone Diva Manglers"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
    ("Matthew Stafford", "Tbone Diva Manglers"): {"years_kept": 2, "prior_cost": 24, "is_undrafted": False},
    ("Jahmyr Gibbs", "TD Master"): {"years_kept": 5, "prior_cost": 1, "is_undrafted": False},
    ("Michael Pittman Jr.", "TD Master"): {"years_kept": 2, "prior_cost": 5, "is_undrafted": False},
    ("Demario Davis", "TD Master"): {"years_kept": 2, "prior_cost": 9, "is_undrafted": False},
    ("Jack Campbell", "TD Master"): {"years_kept": 3, "prior_cost": 11, "is_undrafted": False},
    ("Puka Nacua", "The Cinderella Boyz"): {"years_kept": 4, "prior_cost": 4, "is_undrafted": True},
    ("Javonte Williams", "The Cinderella Boyz"): {"years_kept": 2, "prior_cost": 7, "is_undrafted": False},
    ("Will Anderson Jr.", "The Cinderella Boyz"): {"years_kept": 2, "prior_cost": 13, "is_undrafted": False},
    ("DeMarvion Overshown", "The Cinderella Boyz"): {"years_kept": 2, "prior_cost": 16, "is_undrafted": False},
    ("Ladd McConkey", "Wild Card"): {"years_kept": 3, "prior_cost": 4, "is_undrafted": False},
    ("Daiyan Henley", "Wild Card"): {"years_kept": 3, "prior_cost": 13, "is_undrafted": True},
    ("Justin Herbert", "Wild Card"): {"years_kept": 2, "prior_cost": 18, "is_undrafted": False},
    ("Geno Stone", "Wild Card"): {"years_kept": 2, "prior_cost": 20, "is_undrafted": True},
}

# 2026 Draft Order & Full Results (24 Rounds x 12 Picks = 288 Selections)
# Each entry: (round_num, pick_num, overall_pick, player_name, nfl_team, pos, side, fantasy_team)
DRAFT_RESULTS_2026 = [
    # Round 1
    (1, 1, 1, "Amon-Ra St. Brown", "Det", "WR", "Offense", "SilentXecution"),
    (1, 2, 2, "James Cook III", "Buf", "RB", "Offense", "Samurai"),
    (1, 3, 3, "Christian McCaffrey", "SF", "RB", "Offense", "The Cinderella Boyz"),
    (1, 4, 4, "Saquon Barkley", "Phi", "RB", "Offense", "The Mad Scientist Syndicate"),
    (1, 5, 5, "Bijan Robinson", "Atl", "RB", "Offense", "Super Saiyan"),
    (1, 6, 6, "Jahmyr Gibbs", "Det", "RB", "Offense", "TD Master"),
    (1, 7, 7, "CeeDee Lamb", "Dal", "WR", "Offense", "ninja"),
    (1, 8, 8, "Justin Jefferson", "Min", "WR", "Offense", "MotorBoaters"),
    (1, 9, 9, "Jonathan Taylor", "Ind", "RB", "Offense", "Jack Wagons"),
    (1, 10, 10, "De'Von Achane", "Mia", "RB", "Offense", "RAZINUDOWN"),
    (1, 11, 11, "George Pickens", "Dal", "WR", "Offense", "Wild Card"),
    (1, 12, 12, "Ja'Marr Chase", "Cin", "WR", "Offense", "Tbone Diva Manglers"),
    # Round 2
    (2, 1, 13, "Nico Collins", "Hou", "WR", "Offense", "Tbone Diva Manglers"),
    (2, 2, 14, "Chase Brown", "Cin", "RB", "Offense", "Wild Card"),
    (2, 3, 15, "Derrick Henry", "Bal", "RB", "Offense", "RAZINUDOWN"),
    (2, 4, 16, "Kenneth Walker III", "KC", "RB", "Offense", "Jack Wagons"),
    (2, 5, 17, "Omarion Hampton", "LAC", "RB", "Offense", "MotorBoaters"),
    (2, 6, 18, "A.J. Brown", "NE", "WR", "Offense", "Samurai"),
    (2, 7, 19, "Drake London", "Atl", "WR", "Offense", "TD Master"),
    (2, 8, 20, "Malik Nabers", "NYG", "WR", "Offense", "Super Saiyan"),
    (2, 9, 21, "Kyren Williams", "LAR", "RB", "Offense", "The Mad Scientist Syndicate"),
    (2, 10, 22, "Ashton Jeanty", "LV", "RB", "Offense", "The Cinderella Boyz"),
    (2, 11, 23, "Travis Etienne Jr.", "NO", "RB", "Offense", "ninja"),
    (2, 12, 24, "Braelon Allen", "NYJ", "RB", "Offense", "SilentXecution"),
    # Round 3
    (3, 1, 25, "Garrett Wilson", "NYJ", "WR", "Offense", "SilentXecution"),
    (3, 2, 26, "Breece Hall", "NYJ", "RB", "Offense", "Samurai"),
    (3, 3, 27, "Tyler Warren", "Ind", "TE", "Offense", "The Cinderella Boyz"),
    (3, 4, 28, "D'Andre Swift", "Chi", "RB", "Offense", "The Mad Scientist Syndicate"),
    (3, 5, 29, "Colston Loveland", "Chi", "TE", "Offense", "Super Saiyan"),
    (3, 6, 30, "DeVonta Smith", "Phi", "WR", "Offense", "TD Master"),
    (3, 7, 31, "Zay Flowers", "Bal", "WR", "Offense", "Samurai"),
    (3, 8, 32, "Jaxon Smith-Njigba", "Sea", "WR", "Offense", "MotorBoaters"),
    (3, 9, 33, "Emeka Egbuka", "TB", "WR", "Offense", "Jack Wagons"),
    (3, 10, 34, "Josh Allen", "Buf", "QB", "Offense", "RAZINUDOWN"),
    (3, 11, 35, "Jeremiyah Love", "Ari", "RB", "Offense", "Wild Card"),
    (3, 12, 36, "Jadarian Price", "Sea", "RB", "Offense", "Tbone Diva Manglers"),
    # Round 4
    (4, 1, 37, "Tetairoa McMillan", "Car", "WR", "Offense", "Tbone Diva Manglers"),
    (4, 2, 38, "Ladd McConkey", "LAC", "WR", "Offense", "Wild Card"),
    (4, 3, 39, "Brock Bowers", "LV", "TE", "Offense", "RAZINUDOWN"),
    (4, 4, 40, "Josh Jacobs", "GB", "RB", "Offense", "Jack Wagons"),
    (4, 5, 41, "David Montgomery", "Hou", "RB", "Offense", "MotorBoaters"),
    (4, 6, 42, "Davante Adams", "LAR", "WR", "Offense", "Samurai"),
    (4, 7, 43, "Lamar Jackson", "Bal", "QB", "Offense", "TD Master"),
    (4, 8, 44, "DJ Moore", "Buf", "WR", "Offense", "Super Saiyan"),
    (4, 9, 45, "Luther Burden III", "Chi", "WR", "Offense", "The Mad Scientist Syndicate"),
    (4, 10, 46, "Puka Nacua", "LAR", "WR", "Offense", "The Cinderella Boyz"),
    (4, 11, 47, "Bucky Irving", "TB", "RB", "Offense", "ninja"),
    (4, 12, 48, "Jaylen Warren", "Pit", "RB", "Offense", "SilentXecution"),
    # Round 5
    (5, 1, 49, "Chris Olave", "NO", "WR", "Offense", "SilentXecution"),
    (5, 2, 50, "Tee Higgins", "Cin", "WR", "Offense", "ninja"),
    (5, 3, 51, "Jameson Williams", "Det", "WR", "Offense", "The Cinderella Boyz"),
    (5, 4, 52, "Terry McLaurin", "Was", "WR", "Offense", "The Mad Scientist Syndicate"),
    (5, 5, 53, "Bhayshul Tuten", "Jax", "RB", "Offense", "Super Saiyan"),
    (5, 6, 54, "Michael Pittman Jr.", "Pit", "WR", "Offense", "TD Master"),
    (5, 7, 55, "Rhamondre Stevenson", "NE", "RB", "Offense", "Samurai"),
    (5, 8, 56, "Chuba Hubbard", "Car", "RB", "Offense", "MotorBoaters"),
    (5, 9, 57, "Joe Burrow", "Cin", "QB", "Offense", "Jack Wagons"),
    (5, 10, 58, "Jaylen Waddle", "Den", "WR", "Offense", "RAZINUDOWN"),
    (5, 11, 59, "Kyle Pitts Sr.", "Atl", "TE", "Offense", "Wild Card"),
    (5, 12, 60, "Carnell Tate", "Ten", "WR", "Offense", "Tbone Diva Manglers"),
    # Round 6
    (6, 1, 61, "Quinshon Judkins", "Cle", "RB", "Offense", "Tbone Diva Manglers"),
    (6, 2, 62, "Kenny Gainwell", "TB", "RB", "Offense", "Wild Card"),
    (6, 3, 63, "Parker Washington", "Jax", "WR", "Offense", "RAZINUDOWN"),
    (6, 4, 64, "Sam LaPorta", "Det", "TE", "Offense", "Jack Wagons"),
    (6, 5, 65, "Dak Prescott", "Dal", "QB", "Offense", "MotorBoaters"),
    (6, 6, 66, "Drake Maye", "NE", "QB", "Offense", "ninja"),
    (6, 7, 67, "TreVeyon Henderson", "NE", "RB", "Offense", "TD Master"),
    (6, 8, 68, "Christian Watson", "GB", "WR", "Offense", "Super Saiyan"),
    (6, 9, 69, "Jayden Daniels", "Was", "QB", "Offense", "The Mad Scientist Syndicate"),
    (6, 10, 70, "Brian Thomas Jr.", "Jax", "WR", "Offense", "The Cinderella Boyz"),
    (6, 11, 71, "Trey McBride", "Ari", "TE", "Offense", "ninja"),
    (6, 12, 72, "Khalil Shakir", "Buf", "WR", "Offense", "SilentXecution"),
    # Round 7
    (7, 1, 73, "Jordan Love", "GB", "QB", "Offense", "SilentXecution"),
    (7, 2, 74, "DK Metcalf", "Pit", "WR", "Offense", "ninja"),
    (7, 3, 75, "Javonte Williams", "Dal", "RB", "Offense", "The Cinderella Boyz"),
    (7, 4, 76, "Harold Fannin Jr.", "Cle", "TE", "Offense", "The Mad Scientist Syndicate"),
    (7, 5, 77, "Jalen Hurts", "Phi", "QB", "Offense", "Super Saiyan"),
    (7, 6, 78, "Tucker Kraft", "GB", "TE", "Offense", "TD Master"),
    (7, 7, 79, "Rashee Rice", "KC", "WR", "Offense", "Samurai"),
    (7, 8, 80, "Fred Warner", "SF", "LB", "Defense", "MotorBoaters"),
    (7, 9, 81, "Maxx Crosby", "LV", "DE", "Defense", "Jack Wagons"),
    (7, 10, 82, "Rashid Shaheed", "Sea", "WR", "Offense", "RAZINUDOWN"),
    (7, 11, 83, "Mike Evans", "SF", "WR", "Offense", "Wild Card"),
    (7, 12, 84, "Tony Pollard", "Ten", "RB", "Offense", "Tbone Diva Manglers"),
    # Round 8
    (8, 1, 85, "Foyesade Oluokun", "Jax", "LB", "Defense", "Tbone Diva Manglers"),
    (8, 2, 86, "Roquan Smith", "Bal", "LB", "Defense", "Wild Card"),
    (8, 3, 87, "Sonny Styles", "Was", "LB", "Defense", "RAZINUDOWN"),
    (8, 4, 88, "Chris Godwin Jr.", "TB", "WR", "Offense", "Jack Wagons"),
    (8, 5, 89, "Edgerrin Cooper", "GB", "LB", "Defense", "MotorBoaters"),
    (8, 6, 90, "Travis Kelce", "KC", "TE", "Offense", "Samurai"),
    (8, 7, 91, "Travis Hunter", "Jax", "WR,CB", "Offense", "TD Master"),
    (8, 8, 92, "Jonathon Brooks", "Car", "RB", "Offense", "Super Saiyan"),
    (8, 9, 93, "Nick Bolton", "KC", "LB", "Defense", "The Mad Scientist Syndicate"),
    (8, 10, 94, "Bo Nix", "Den", "QB", "Offense", "The Cinderella Boyz"),
    (8, 11, 95, "Alec Pierce", "Ind", "WR", "Offense", "ninja"),
    (8, 12, 96, "Hunter Henry", "NE", "TE", "Offense", "SilentXecution"),
    # Round 9
    (9, 1, 97, "KC Concepcion", "Cle", "WR", "Offense", "SilentXecution"),
    (9, 2, 98, "Derwin James Jr.", "LAC", "S", "Defense", "ninja"),
    (9, 3, 99, "Courtland Sutton", "Den", "WR", "Offense", "The Cinderella Boyz"),
    (9, 4, 100, "Cooper DeJean", "Phi", "DB,CB", "Defense", "The Mad Scientist Syndicate"),
    (9, 5, 101, "Jordyn Brooks", "Mia", "LB", "Defense", "Super Saiyan"),
    (9, 6, 102, "Demario Davis", "NYJ", "LB", "Defense", "TD Master"),
    (9, 7, 103, "T.J. Edwards", "Chi", "LB", "Defense", "Samurai"),
    (9, 8, 104, "George Kittle", "SF", "TE", "Offense", "MotorBoaters"),
    (9, 9, 105, "Brandon Aubrey", "Dal", "K", "Special Teams", "Jack Wagons"),
    (9, 10, 106, "Marvin Harrison Jr.", "Ari", "WR", "Offense", "RAZINUDOWN"),
    (9, 11, 107, "Aaron Jones Sr.", "Min", "RB", "Offense", "Wild Card"),
    (9, 12, 108, "Zaire Franklin", "GB", "LB", "Defense", "Tbone Diva Manglers"),
    # Round 10
    (10, 1, 109, "Jake Ferguson", "Dal", "TE", "Offense", "Tbone Diva Manglers"),
    (10, 2, 110, "Josh Downs", "Ind", "WR", "Offense", "Wild Card"),
    (10, 3, 111, "Blake Cashman", "Min", "LB", "Defense", "RAZINUDOWN"),
    (10, 4, 112, "Divine Deablo", "Atl", "LB", "Defense", "Jack Wagons"),
    (10, 5, 113, "Rico Dowdle", "Pit", "RB", "Offense", "MotorBoaters"),
    (10, 6, 114, "Kyle Hamilton", "Bal", "S", "Defense", "Samurai"),
    (10, 7, 115, "Marcus Jones", "NE", "DB,CB", "Defense", "TD Master"),
    (10, 8, 116, "Rome Odunze", "Chi", "WR", "Offense", "Super Saiyan"),
    (10, 9, 117, "Jayden Reed", "GB", "WR", "Offense", "The Mad Scientist Syndicate"),
    (10, 10, 118, "Nakobe Dean", "LV", "LB", "Defense", "The Cinderella Boyz"),
    (10, 11, 119, "Jacory Croskey-Merritt", "Was", "RB", "Offense", "ninja"),
    (10, 12, 120, "Jordan Mason", "Min", "RB", "Offense", "SilentXecution"),
    # Round 11
    (11, 1, 121, "Caleb Williams", "Chi", "QB", "Offense", "SilentXecution"),
    (11, 2, 122, "Jordan Addison", "Min", "WR", "Offense", "ninja"),
    (11, 3, 123, "Nick Cross", "Was", "S", "Defense", "The Cinderella Boyz"),
    (11, 4, 124, "Julian Love", "Sea", "S", "Defense", "The Mad Scientist Syndicate"),
    (11, 5, 125, "Jordyn Tyson", "NO", "WR", "Offense", "Super Saiyan"),
    (11, 6, 126, "Jack Campbell", "Det", "LB", "Defense", "TD Master"),
    (11, 7, 127, "Myles Garrett", "LAR", "LB,DE", "Defense", "Samurai"),
    (11, 8, 128, "Dalton Kincaid", "Buf", "TE", "Offense", "MotorBoaters"),
    (11, 9, 129, "Jeffery Simmons", "Ten", "DT,DE", "Defense", "Jack Wagons"),
    (11, 10, 130, "Chamarri Conner", "KC", "DB,S", "Defense", "RAZINUDOWN"),
    (11, 11, 131, "RJ Harvey", "Den", "RB", "Offense", "Wild Card"),
    (11, 12, 132, "J.K. Dobbins", "Den", "RB", "Offense", "Tbone Diva Manglers"),
    # Round 12
    (12, 1, 133, "Robert Spillane", "NE", "LB", "Defense", "Tbone Diva Manglers"),
    (12, 2, 134, "Brian Burns", "NYG", "LB,DE", "Defense", "Wild Card"),
    (12, 3, 135, "Jamien Sherwood", "NYJ", "LB", "Defense", "RAZINUDOWN"),
    (12, 4, 136, "Jakobi Meyers", "Jax", "WR", "Offense", "Jack Wagons"),
    (12, 5, 137, "Stefon Diggs", "Was", "WR", "Offense", "MotorBoaters"),
    (12, 6, 138, "Carson Schwesinger", "Cle", "LB", "Defense", "Samurai"),
    (12, 7, 139, "Juanyeh Thomas", "Ind", "S", "Defense", "TD Master"),
    (12, 8, 140, "Kaden Elliss", "NO", "LB", "Defense", "Super Saiyan"),
    (12, 9, 141, "Devin White", "Det", "LB", "Defense", "The Mad Scientist Syndicate"),
    (12, 10, 142, "Leonard Williams", "Sea", "DL,DT,DE", "Defense", "The Cinderella Boyz"),
    (12, 11, 143, "T.J. Watt", "Pit", "LB,DE", "Defense", "ninja"),
    (12, 12, 144, "Ernest Jones IV", "Sea", "LB", "Defense", "SilentXecution"),
    # Round 13
    (13, 1, 145, "Blake Corum", "LAR", "RB", "Offense", "SilentXecution"),
    (13, 2, 146, "Alontae Taylor", "Ten", "CB", "Defense", "ninja"),
    (13, 3, 147, "Will Anderson Jr.", "Hou", "DE", "Defense", "The Cinderella Boyz"),
    (13, 4, 148, "Jaxson Dart", "NYG", "QB", "Offense", "The Mad Scientist Syndicate"),
    (13, 5, 149, "Zack Baun", "Phi", "LB", "Defense", "Super Saiyan"),
    (13, 6, 150, "Jalen Reeves-Maybin", "Chi", "LB", "Defense", "TD Master"),
    (13, 7, 151, "Cam Skattebo", "NYG", "RB", "Offense", "Samurai"),
    (13, 8, 152, "Demetrius Knight Jr.", "Cin", "LB", "Defense", "MotorBoaters"),
    (13, 9, 153, "Michael Wilson", "Ari", "WR", "Offense", "Jack Wagons"),
    (13, 10, 154, "Chimere Dike", "Ten", "WR", "Offense", "RAZINUDOWN"),
    (13, 11, 155, "Daiyan Henley", "LAC", "LB", "Defense", "Wild Card"),
    (13, 12, 156, "De'Zhaun Stribling", "SF", "WR", "Offense", "Tbone Diva Manglers"),
    # Round 14
    (14, 1, 157, "Jared Verse", "Cle", "DL,LB,DE", "Defense", "Tbone Diva Manglers"),
    (14, 2, 158, "Matthew Golden", "GB", "WR", "Offense", "Wild Card"),
    (14, 3, 159, "Tykee Smith", "TB", "DB,S", "Defense", "RAZINUDOWN"),
    (14, 4, 160, "Malachi Lawrence", "Dal", "LB,DE", "Defense", "Jack Wagons"),
    (14, 5, 161, "Kyle Monangai", "Chi", "RB", "Offense", "MotorBoaters"),
    (14, 6, 162, "Trevor Lawrence", "Jax", "QB", "Offense", "Samurai"),
    (14, 7, 163, "Ta'Quon Graham", "Phi", "DL,DE", "Defense", "TD Master"),
    (14, 8, 164, "Patrick Mahomes", "KC", "QB", "Offense", "Super Saiyan"),
    (14, 9, 165, "Alex Singleton", "Den", "LB", "Defense", "The Mad Scientist Syndicate"),
    (14, 10, 166, "Trey Hendrickson", "Bal", "LB,DE", "Defense", "The Cinderella Boyz"),
    (14, 11, 167, "DaRon Bland", "Dal", "CB", "Defense", "ninja"),
    (14, 12, 168, "Terrance Ferguson", "LAR", "TE", "Offense", "SilentXecution"),
    # Round 15
    (15, 1, 169, "Quincy Williams", "Cle", "LB", "Defense", "SilentXecution"),
    (15, 2, 170, "Ventrell Miller", "Jax", "LB", "Defense", "ninja"),
    (15, 3, 171, "Derek Stingley Jr.", "Hou", "CB", "Defense", "The Cinderella Boyz"),
    (15, 4, 172, "Quinnen Williams", "Dal", "DL,DT", "Defense", "The Mad Scientist Syndicate"),
    (15, 5, 173, "Mike Washington Jr.", "LV", "RB", "Offense", "Super Saiyan"),
    (15, 6, 174, "Jeremiah Pharms Jr.", "NE", "DL,DT,DE", "Defense", "TD Master"),
    (15, 7, 175, "Nick Emmanwori", "Sea", "S", "Defense", "Samurai"),
    (15, 8, 176, "Jonah Coleman", "Den", "RB", "Offense", "MotorBoaters"),
    (15, 9, 177, "Makai Lemon", "Phi", "WR", "Offense", "Jack Wagons"),
    (15, 10, 178, "Kamari Lassiter", "Hou", "DB,CB", "Defense", "RAZINUDOWN"),
    (15, 11, 179, "Kevin Byard III", "NE", "S", "Defense", "Wild Card"),
    (15, 12, 180, "Zach Charbonnet", "Sea", "RB", "Offense", "Tbone Diva Manglers"),
    # Round 16
    (16, 1, 181, "Akeem Davis-Gaither", "Ind", "LB", "Defense", "Tbone Diva Manglers"),
    (16, 2, 182, "Deebo Samuel Sr.", "SF", "WR", "Offense", "Wild Card"),
    (16, 3, 183, "KaVontae Turpin", "Dal", "WR", "Offense", "RAZINUDOWN"),
    (16, 4, 184, "LT Overton", "Dal", "DE", "Defense", "Jack Wagons"),
    (16, 5, 185, "Malaki Starks", "Bal", "S", "Defense", "MotorBoaters"),
    (16, 6, 186, "Malik Willis", "Mia", "QB", "Offense", "Samurai"),
    (16, 7, 187, "Quentin Johnston", "LAC", "WR", "Offense", "TD Master"),
    (16, 8, 188, "Jessie Bates III", "Atl", "S", "Defense", "Super Saiyan"),
    (16, 9, 189, "Aidan Hutchinson", "Det", "DL,DE", "Defense", "The Mad Scientist Syndicate"),
    (16, 10, 190, "DeMarvion Overshown", "Dal", "LB", "Defense", "The Cinderella Boyz"),
    (16, 11, 191, "Quay Walker", "LV", "LB", "Defense", "ninja"),
    (16, 12, 192, "Barrett Carter", "Cin", "LB", "Defense", "SilentXecution"),
    # Round 17
    (17, 1, 193, "Jordan Battle", "Cin", "S", "Defense", "SilentXecution"),
    (17, 2, 194, "Budda Baker", "Ari", "S", "Defense", "ninja"),
    (17, 3, 195, "Nik Bonitto", "Den", "LB,DE", "Defense", "The Cinderella Boyz"),
    (17, 4, 196, "Jason Myers", "Sea", "K", "Special Teams", "The Mad Scientist Syndicate"),
    (17, 5, 197, "Devon Witherspoon", "Sea", "CB", "Defense", "Super Saiyan"),
    (17, 6, 198, "Brock Purdy", "SF", "QB", "Offense", "TD Master"),
    (17, 7, 199, "Terrel Bernard", "Buf", "LB", "Defense", "Samurai"),
    (17, 8, 200, "Tyson Campbell", "Cle", "CB", "Defense", "MotorBoaters"),
    (17, 9, 201, "Malachi Moore", "NYJ", "S", "Defense", "Jack Wagons"),
    (17, 10, 202, "David Bailey", "NYJ", "LB,DE", "Defense", "RAZINUDOWN"),
    (17, 11, 203, "Patrick Queen", "Pit", "LB", "Defense", "Wild Card"),
    (17, 12, 204, "Caleb Downs", "Dal", "S", "Defense", "Tbone Diva Manglers"),
    # Round 18
    (18, 1, 205, "Kam Curl", "LAR", "S", "Defense", "Tbone Diva Manglers"),
    (18, 2, 206, "Justin Herbert", "LAC", "QB", "Offense", "Wild Card"),
    (18, 3, 207, "Arvell Reese", "NYG", "LB", "Defense", "RAZINUDOWN"),
    (18, 4, 208, "Deonte Banks", "NYG", "CB", "Defense", "Jack Wagons"),
    (18, 5, 209, "L.J. Collier", "Ari", "DL,DE", "Defense", "MotorBoaters"),
    (18, 6, 210, "DeForest Buckner", "Ind", "DT", "Defense", "Samurai"),
    (18, 7, 211, "Chris Rodriguez Jr.", "Jax", "RB", "Offense", "TD Master"),
    (18, 8, 212, "Danielle Hunter", "Hou", "LB,DE", "Defense", "Super Saiyan"),
    (18, 9, 213, "Jalen Coker", "Car", "WR", "Offense", "The Mad Scientist Syndicate"),
    (18, 10, 214, "Dallas Goedert", "Phi", "TE", "Offense", "The Cinderella Boyz"),
    (18, 11, 215, "Rachaad White", "Was", "RB", "Offense", "ninja"),
    (18, 12, 216, "Alex Anzalone", "TB", "LB", "Defense", "SilentXecution"),
    # Round 19
    (19, 1, 217, "Xavier Watts", "Atl", "S", "Defense", "SilentXecution"),
    (19, 2, 218, "Nick Bosa", "SF", "DL,DE", "Defense", "ninja"),
    (19, 3, 219, "Cameron Heyward", "Pit", "DT,DE", "Defense", "The Cinderella Boyz"),
    (19, 4, 220, "Tre'von Moehrig", "Car", "S", "Defense", "The Mad Scientist Syndicate"),
    (19, 5, 221, "Josiah Trotter", "TB", "LB", "Defense", "Super Saiyan"),
    (19, 6, 222, "Isaiah Likely", "NYG", "TE", "Offense", "TD Master"),
    (19, 7, 223, "Mark Andrews", "Bal", "TE", "Offense", "Samurai"),
    (19, 8, 224, "Dee Winters", "Dal", "LB", "Defense", "MotorBoaters"),
    (19, 9, 225, "Dane Belton", "NYJ", "S", "Defense", "Jack Wagons"),
    (19, 10, 226, "Kyler Murray", "Min", "QB", "Offense", "RAZINUDOWN"),
    (19, 11, 227, "Andrew Van Ginkel", "Min", "LB,DE", "Defense", "Wild Card"),
    (19, 12, 228, "Mike Sainristil", "Was", "DB,CB", "Defense", "Tbone Diva Manglers"),
    # Round 20
    (20, 1, 229, "Devin Bush", "Chi", "LB", "Defense", "Tbone Diva Manglers"),
    (20, 2, 230, "Geno Stone", "Buf", "S", "Defense", "Wild Card"),
    (20, 3, 231, "Tuli Tuipulotu", "LAC", "LB,DE", "Defense", "RAZINUDOWN"),
    (20, 4, 232, "Nate Landman", "LAR", "LB", "Defense", "Jack Wagons"),
    (20, 5, 233, "Tyrel Dodson", "Car", "LB", "Defense", "MotorBoaters"),
    (20, 6, 234, "Cedric Gray", "Ten", "LB", "Defense", "Samurai"),
    (20, 7, 235, "Josh Blackwell", "Chi", "DB,CB", "Defense", "TD Master"),
    (20, 8, 236, "Brian Robinson", "Atl", "RB", "Offense", "Super Saiyan"),
    (20, 9, 237, "Tremaine Edmunds", "NYG", "LB", "Defense", "The Mad Scientist Syndicate"),
    (20, 10, 238, "Cameron Dicker", "LAC", "K", "Special Teams", "The Cinderella Boyz"),
    (20, 11, 239, "Devin Lloyd", "Car", "LB", "Defense", "ninja"),
    (20, 12, 240, "Joshua Metellus", "Min", "S,CB", "Defense", "SilentXecution"),
    # Round 21
    (21, 1, 241, "Abdul Carter", "NYG", "LB,DE", "Defense", "SilentXecution"),
    (21, 2, 242, "Ka'imi Fairbairn", "Hou", "K", "Special Teams", "ninja"),
    (21, 3, 243, "Marlon Humphrey", "Bal", "CB", "Defense", "The Cinderella Boyz"),
    (21, 4, 244, "Malik Washington", "Mia", "WR", "Offense", "The Mad Scientist Syndicate"),
    (21, 5, 245, "Byron Murphy II", "Sea", "DT", "Defense", "Super Saiyan"),
    (21, 6, 246, "Ashtyn Davis", "SF", "S", "Defense", "TD Master"),
    (21, 7, 247, "Paulson Adebo", "NYG", "CB", "Defense", "Samurai"),
    (21, 8, 248, "Jordon Riley", "GB", "DL,DT", "Defense", "MotorBoaters"),
    (21, 9, 249, "Tyler Allgeier", "Ari", "RB", "Offense", "Jack Wagons"),
    (21, 10, 250, "Rueben Bain Jr.", "TB", "LB,DE", "Defense", "RAZINUDOWN"),
    (21, 11, 251, "Drue Tranquill", "KC", "LB", "Defense", "Wild Card"),
    (21, 12, 252, "Dexter Lawrence II", "Cin", "DL,DT", "Defense", "Tbone Diva Manglers"),
    # Round 22
    (22, 1, 253, "Eddy Pineiro", "SF", "K", "Special Teams", "Tbone Diva Manglers"),
    (22, 2, 254, "Mike Jackson", "Car", "CB", "Defense", "Wild Card"),
    (22, 3, 255, "Tyler Loop", "Bal", "K", "Special Teams", "RAZINUDOWN"),
    (22, 4, 256, "Dalton Schultz", "Hou", "TE", "Offense", "Jack Wagons"),
    (22, 5, 257, "Harrison Mevis", "LAR", "K", "Special Teams", "MotorBoaters"),
    (22, 6, 258, "Azeez Al-Shaair", "Hou", "LB", "Defense", "Samurai"),
    (22, 7, 259, "Rodney Thomas II", "Sea", "S", "Defense", "TD Master"),
    (22, 8, 260, "Cam Little", "Jax", "K", "Special Teams", "Super Saiyan"),
    (22, 9, 261, "Wan'Dale Robinson", "Ten", "WR", "Offense", "The Mad Scientist Syndicate"),
    (22, 10, 262, "Jared Goff", "Det", "QB", "Offense", "The Cinderella Boyz"),
    (22, 11, 263, "Brenton Strange", "Jax", "TE", "Offense", "ninja"),
    (22, 12, 264, "Jihaad Campbell", "Phi", "LB", "Defense", "SilentXecution"),
    # Round 23
    (23, 1, 265, "Derrick Brown", "Car", "DT,DE", "Defense", "SilentXecution"),
    (23, 2, 266, "Jalen Carter", "Phi", "DT,DE", "Defense", "ninja"),
    (23, 3, 267, "Troy Franklin", "Den", "WR", "Offense", "The Cinderella Boyz"),
    (23, 4, 268, "Tre Tucker", "LV", "WR", "Offense", "The Mad Scientist Syndicate"),
    (23, 5, 269, "Jaishawn Barham", "Dal", "LB,DE", "Defense", "Super Saiyan"),
    (23, 6, 270, "Drake Jackson", "Was", "DL,DE", "Defense", "TD Master"),
    (23, 7, 271, "Upton Stout", "SF", "CB", "Defense", "Samurai"),
    (23, 8, 272, "Romeo Doubs", "NE", "WR", "Offense", "MotorBoaters"),
    (23, 9, 273, "Isaiah Pola-Mao", "LV", "S", "Defense", "Jack Wagons"),
    (23, 10, 274, "Peter Woods", "KC", "DT", "Defense", "RAZINUDOWN"),
    (23, 11, 275, "Mason Graham", "Cle", "DT", "Defense", "Wild Card"),
    (23, 12, 276, "Woody Marks", "Hou", "RB", "Offense", "Tbone Diva Manglers"),
    # Round 24
    (24, 1, 277, "Matthew Stafford", "LAR", "QB", "Offense", "Tbone Diva Manglers"),
    (24, 2, 278, "Tyler Bass", "Buf", "K", "Special Teams", "Wild Card"),
    (24, 3, 279, "Joey Slye", "Ten", "K", "Special Teams", "RAZINUDOWN"),
    (24, 4, 280, "Marcus Epps", "Phi", "S", "Defense", "Jack Wagons"),
    (24, 5, 281, "Jaydon Blue", "Phi", "RB", "Offense", "MotorBoaters"),
    (24, 6, 282, "Harrison Butker", "KC", "K", "Special Teams", "Samurai"),
    (24, 7, 283, "Will Reichard", "Min", "K", "Special Teams", "TD Master"),
    (24, 8, 284, "DeShon Elliott", "Pit", "S", "Defense", "Super Saiyan"),
    (24, 9, 285, "Denzel Boston", "Cle", "WR", "Offense", "The Mad Scientist Syndicate"),
    (24, 10, 286, "Tyrone Tracy Jr.", "NYG", "RB", "Offense", "The Cinderella Boyz"),
    (24, 11, 287, "Austin Booker", "Chi", "DL,DE", "Defense", "ninja"),
    (24, 12, 288, "Jake Bates", "Det", "K", "Special Teams", "SilentXecution"),
]


def get_team_roster(team_name: str):
    """Returns the 24 drafted players for a given team, mapped with keeper status."""
    roster = []
    for row in DRAFT_RESULTS_2026:
        rd, pk, ovr, player, nfl, pos, side, f_team = row
        if f_team == team_name:
            kh = KEEPER_HISTORY.get((player, team_name))
            if kh:
                years_kept = kh["years_kept"]
                prior_cost = kh["prior_cost"]
                is_undrafted = kh["is_undrafted"]
            else:
                years_kept = 1  # 2026 was their first draft year
                prior_cost = rd
                is_undrafted = False

            roster.append({
                "name": player,
                "nfl_team": nfl,
                "position": pos,
                "side": side,
                "draft_round": rd,
                "overall_pick": ovr,
                "years_kept": years_kept,
                "prior_cost": prior_cost,
                "is_undrafted": is_undrafted,
            })
    return sorted(roster, key=lambda x: x["draft_round"])